apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-setup
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/setup
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Replace=true
